spark.master                     spark://spark-master:7077
spark.sql.catalogImplementation  hive
spark.hadoop.hive.metastore.uris thrift://metastore:9083

# để spark có thể giao tiếp với minio
spark.hadoop.fs.s3a.endpoint     http://minio:9000
spark.hadoop.fs.s3a.access.key   root
spark.hadoop.fs.s3a.secret.key   password
spark.hadoop.fs.s3a.path.style.access true
spark.hadoop.fs.s3a.impl         org.apache.hadoop.fs.s3a.S3AFileSystem

# Cài những thư viện cần thiết cho spark
spark.jars.packages              org.apache.hadoop:hadoop-aws:3.3.4,com.amazonaws:aws-java-sdk-bundle:1.12.262
