spark.master                     spark://spark-master:7077
spark.sql.catalogImplementation  hive
spark.hadoop.hive.metastore.uris thrift://metastore:9083

# để spark có thể giao tiếp với minio
spark.hadoop.fs.s3a.endpoint     http://minio:9000
spark.hadoop.fs.s3a.access.key   root
spark.hadoop.fs.s3a.secret.key   password
spark.hadoop.fs.s3a.path.style.access true
spark.hadoop.fs.s3a.impl         org.apache.hadoop.fs.s3a.S3AFileSystem

# Cài những thư viện cần thiết cho spark và iceberg
spark.jars.packages              org.postgresql:postgresql:42.6.0,org.apache.hadoop:hadoop-aws:3.3.4,com.amazonaws:aws-java-sdk-bundle:1.12.262,org.apache.iceberg:iceberg-spark-runtime-3.4_2.12:1.4.1

# Cấu hình Iceberg Catalog
spark.sql.extensions             org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
spark.sql.catalog.spark_catalog  org.apache.iceberg.spark.SparkSessionCatalog
spark.sql.catalog.spark_catalog.type hive
spark.sql.catalog.my_catalog     org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.my_catalog.type hive
spark.sql.catalog.my_catalog.uri thrift://metastore:9083
spark.sql.catalog.my_catalog.warehouse s3a://sandbox/warehouse/
